version: '2'
services:
    dexter-app:
        image: dexter
        external_links:
            - dexter-postgresql:postgresql
            - dexter-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/dexter
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    dexter-postgresql:
        extends:
            file: postgresql.yml
            service: dexter-postgresql
    dexter-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dexter-elasticsearch
